fsca/fsca/Controllers/PaymentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace fsca.Controllers
{
    public class PaymentController : Controller
    {
        // GET: Payment
        public ActionResult Checkout()
        {
            return View();
        }

        public ActionResult Payment()
        {
            return View();
        }

        public ActionResult PaymentSuccess()
        {
            return View();
        }

        public ActionResult PaymentFailure()
        {
            return View();
        }
    }
}

fsca/fsca/Views/Shared/LoginRegister.cshtml
@if(Session["accountName"] != null)
{
    <span>@Session["accountName"], you are logged in.</span>
    @*link below has class equal to right for css*@
    @Html.ActionLink("Logout","Logout","Home",null,new { @class="right"})

}
else
{@*links below has class equal to right for css*@
@Html.ActionLink("Create Account","CreateAcc","Account", null, new { @class="right"})
@Html.ActionLink("Login /", "Login", "Home", null, new { @class = "right" })
}

fsca/fsca/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - FlopShop</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <header>
        @RenderPage("LoginRegister.chstml")
        @RenderSection("Logged",false)


    </header>

    <nav>
     
        @Html.ActionLink("Products", "Products", "Home") &nbsp;&nbsp;
        @Html.ActionLink("Log in", "Login", "Account") &nbsp;&nbsp;
        @Html.ActionLink("Create Account", "CreateAcc", "Account") &nbsp;&nbsp;
        @Html.ActionLink("My Account", "MyAccount", "Account") &nbsp;&nbsp;
        @Html.ActionLink("Shopping Cart", "ShoppingCart", "Account") &nbsp;&nbsp;
        @Html.ActionLink("Checkout", "Checkout", "Payment") &nbsp;&nbsp;
        
        
    </nav>


    
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>